### ISSUE TITLE
Installation crashed due to missing 'nose'

### ISSUE THREAD

**Issue by yhoogstrate** [ErasmusMC-Bioinformatics/crossmap_galaxy_wrapper#1]
STDERR
Download error on https://pypi.python.org/simple/nose/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'nose' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or download links found for nose>=0.10.4
Traceback (most recent call last):
  File "setup.py", line 260, in <module>
    main()
  File "setup.py", line 90, in main
    cmdclass=cmdclass )
  File ".../package_python_2_7/44bb4258922f/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 261, in __init__
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 286, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 631, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 871, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 883, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 337, in fetch_build_egg
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 607, in easy_install
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=0.10.4')

**Comment by yhoogstrate** [comment]
This is fixed in https://github.com/ErasmusMC-Bioinformatics/crossmap_galaxy_wrapper/commit/57442937bd033fc81ade241195d6584d5ca01503
