### ISSUE TITLE
Package crossmap 0.2 compilation error

### ISSUE THREAD

**Issue by JJAlmagro** [ErasmusMC-Bioinformatics/crossmap_galaxy_wrapper#5]
Hello,
I was trying to install crossmap from the Galaxy toolshed and all packages were installed correctly with the exception of the package_crossmap_0_2. This is the stderr:

```
Traceback (most recent call last):
  File "setup.py", line 260, in <module>
    main()
  File "setup.py", line 90, in main
    cmdclass=cmdclass )
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 61, in run
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/steno-internal/projects/galaxy/galaxy-dist/software/cython/0.23.1/iuc/package_cython_0_23_1/45abfe2b0cfc/lib/python/Cython/Distutils/build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/steno-internal/projects/galaxy/galaxy-dist/software/cython/0.23.1/iuc/package_cython_0_23_1/45abfe2b0cfc/lib/python/Cython/Distutils/build_ext.py", line 171, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/cython/0.23.1/iuc/package_cython_0_23_1/45abfe2b0cfc/lib/python/Cython/Distutils/build_ext.py", line 182, in cython_sources
    from Cython.Compiler.Main \
  File "/steno-internal/projects/galaxy/galaxy-dist/software/cython/0.23.1/iuc/package_cython_0_23_1/45abfe2b0cfc/lib/python/Cython/Compiler/Main.py", line 30, in <module>
    from .Symtab import ModuleScope
  File "/steno-internal/projects/galaxy/galaxy-dist/software/cython/0.23.1/iuc/package_cython_0_23_1/45abfe2b0cfc/lib/python/Cython/Compiler/Symtab.py", line 18, in <module>
    from . import PyrexTypes
  File "/steno-internal/projects/galaxy/galaxy-dist/software/cython/0.23.1/iuc/package_cython_0_23_1/45abfe2b0cfc/lib/python/Cython/Compiler/PyrexTypes.py", line 15, in <module>
    from .Code import UtilityCode, LazyUtilityCode, TempitaUtilityCode
  File "Cython/Compiler/Code.py", line 822, in init Cython.Compiler.Code (/isilon/NextGenSeqData/galaxy-data/database/tmp/tmp-toolshed-mtdR4VK4p/Cython-0.23.1/Cython/Compiler/Code.c:73971)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/steno-internal/projects/galaxy/galaxy-dist/software/python/2.7.10/iuc/package_python_2_7_10/73631e818d3d/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unexpected end of regular expression
```

Do you know what could be the problem?

Best regards,
Jose

**Comment by yhoogstrate** [comment]
@JJAlmagro This package has installation problems, mostly because dependencies are compiled with different versions (and different compilation settings like UTF8) of python, and some others are installed by CrossMap's setup.py itself. Around GCC2016 the IUC-tools will move to using (bio-)conda dependencies and I think I want to wait until that transition before making all these changes because I have already spend a lot of time into it... I hope you understand the situation.

Anyway, thanks for reporting the issue and I admit that this wrapper needs to get an update.

**Comment by JJAlmagro** [comment]
Ok, don't worry I understand the situation.
Thank you for your answer!

Best regards,
Jose

**Comment by yhoogstrate** [comment]
@JJAlmagro It seems the time is there to reconsider fixing this issue :)

**Comment by yhoogstrate** [comment]
@JJAlmagro I have rewritten the tool working with BioConda. It is currently under review in tools-iuc's github channel.
